### ISSUE TITLE
构建镜像失败

### ISSUE THREAD

**Issue by kokojacket** [kingmo888/rustdesk-api-server#6]
实在是不好意思，我是小白，使用portainer构建镜像失败了
日志显示
`cannot mount volume over existing file, file exists /share/CACHEDEV1_DATA/docker/container-station-data/lib/docker/overlay2/8f60a7207f46b2219a89bc0c4c9a006f98dba2bfadd3d5432cf13d7b2200ca54/merged/rustdesk-api-server/db.sqlite3`
请问有已经上传到dockerhub上的镜像可供拉取吗？
![image](https://github.com/kingmo888/rustdesk-api-server/assets/74887370/5de9fd4b-78a7-4f25-b712-7fef787fc9b8)

**Comment by Cp0204** [comment]
我尝试构建了一版，试试

### docker-compose
```yaml
version: "3.8"
services:
  rustdesk-api-server:
    container_name: rustdesk-api-server
    image: ghcr.io/cp0204/rustdesk-api-server:master
    environment:
      - HOST=0.0.0.0
      - TZ=Asia/Shanghai
      - CSRF_TRUSTED_ORIGINS=http://yourdomain.com:21114
    volumes:
      - /yourpath/db:/rustdesk-api-server/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - "21114:21114"
    restart: unless-stopped
```
### docker run
```bash
docker run -d \
  --name rustdesk-api-server \
  -p 21114:21114 \
  -e HOST=0.0.0.0 \
  -e TZ=Asia/Shanghai \
  -e CSRF_TRUSTED_ORIGINS=http://yourdomain.com:21114 \
  -v /yourpath/db:/rustdesk-api-server/db \
  -v /etc/timezone:/etc/timezone:ro \
  -v /etc/localtime:/etc/localtime:ro \
  --network bridge \
  --restart unless-stopped \
  ghcr.io/cp0204/rustdesk-api-server:master
```

**Comment by Cp0204** [comment]
集合本项目、官方中转，完整的docker-compose：
```yaml
version: '3.8'

services:

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    volumes:
      - /DATA/AppData/rustdesk-server/hbbr:/root
    network_mode: bridge
    ports:
      - "21117:21117/tcp"
      - "21119:21119/tcp"
    privileged: false

  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    restart: unless-stopped
    depends_on:
      - hbbr
    volumes:
      - /DATA/AppData/rustdesk-server/hbbs:/root
    network_mode: bridge
    ports:
      - "21115:21115/tcp"
      - "21118:21118/tcp"
      - "21116:21116/tcp"
      - "21116:21116/udp"
    privileged: false

  rustdesk-api-server:
    container_name: rustdesk-api-server
    image: ghcr.io/cp0204/rustdesk-api-server:master
    restart: unless-stopped
    environment:
      - CSRF_TRUSTED_ORIGINS=http://chome.0x69.win:21114
      - HOST=0.0.0.0
      - TZ=Asia/Shanghai
    ports:
      - "21114:21114/tcp"
    volumes:
      - /DATA/AppData/rustdesk-server/api/db:/rustdesk-api-server/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    privileged: false
```
